name: bors

on:
  push:
    branches: [ main, staging, trying ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Enable caching'
      uses: Swatinem/rust-cache@v1.3.0
      
    - uses: actions/checkout@v2
    
    - name: 'Clippy'
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
        
    - name: 'Build'
      run: cargo build --verbose
      
    - name: 'Run tests'
      run: cargo test --verbose
