name: coverage

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: 'test'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, macos]
        include:
        - build: stable
          os: ubuntu-latest
          rust: nightly
        - build: macos
          os: macos-latest
          rust: nightly
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 1
        
    - name: 'Enable caching'
      uses: Swatinem/rust-cache@v1.3.0
      
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
