name: Publish on crates.io

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: 'publish'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, win-msvc, win-gnu]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
        - build: macos
          os: macos-latest
          rust: stable
        - build: win-msvc
          os: windows-latest
          rust: stable
        - build: win-gnu
          os: windows-2019
          rust: stable-x86_64-gnu
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 1
        
    - name: 'Install Rust'
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: default
        
    - name: 'Enable caching'
      uses: Swatinem/rust-cache@v1.3.0

    - name: 'Publish on crates.io'
      uses: actions-rs/cargo@v1.0.1
      with:
        command: publish
        args: --verbose --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
